# Generated by Django 5.1.2 on 2025-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
