# Generated by Django 5.1.2 on 2025-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_try_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='guesses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
